name: fireactions-smoke

on:
  push:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_id: [1, 2, 3, 4, 5]
    steps:
      - name: Smoke test ${{ matrix.runner_id }}
        run: echo "smoke OK from runner ${{ matrix.runner_id }} — run_id=${GITHUB_RUN_ID}"
