name: fireactions-smoke

on:
  push:
  workflow_dispatch:

# avoid overlapping on same branch
concurrency:
  group: fireactions-smoke-${{ github.ref }}
  cancel-in-progress: false

jobs:
  smoke:
    name: smoke-${{ matrix.idx }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        idx: [1, 2, 3, 4, 5]
    steps:
      - name: Smoke ${{ matrix.idx }}
        run: |
          echo "smoke OK from runner ${{ matrix.idx }} — run_id=${GITHUB_RUN_ID}"
          # add any quick health checks here if needed

  verify:
    name: verify-all
    needs: [smoke]
    runs-on: ubuntu-latest
    steps:
      - name: Show matrix results
        run: echo "results=${{ join(needs.*.result, ',') }}"
      - name: Assert all 5 succeeded
        run: |
          RESULTS="${{ join(needs.*.result, ',') }}"
          if echo "$RESULTS" | grep -E 'failure|cancelled'; then
            echo "One or more matrix jobs failed or were cancelled: $RESULTS"
            exit 1
          fi
          echo "All 5 parallel runners completed successfully ✅"
