name: self-hosted-smoke

on:
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: [self-hosted, fireactions]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "🔥 Self-hosted runner is alive on $(hostname) at $(date)"
