name: self-hosted-smoke
on:
  push:
  workflow_dispatch:

jobs:
  smoke:
    name: smoke-${{ matrix.idx }}
    runs-on: [self-hosted, fireactions]   # <- must match your pool labels
    strategy:
      fail-fast: false
      matrix: { idx: [1, 2, 3, 4, 5] }
    steps:
      - name: Evidence:runner identity
        run: |
          echo "RUNNER_NAME=${{ runner.name }}"
          echo "RUNNER_OS=${{ runner.os }}"
          echo "RUNNER_ARCH=${{ runner.arch }}"
      - name: Evidence:kernel & container host
        run: |
          uname -a
          whoami
          cat /etc/issue || true
      - name: Smoke ${{ matrix.idx }}
        run: echo "smoke OK from ${{ runner.name }} — idx=${{ matrix.idx }} run_id=${GITHUB_RUN_ID}"
