name: Self-hosted Smoke Test

on:
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: [self-hosted, fireactions]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run hello
        run: echo "Runner $(hostname) is alive"
